# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: migration.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'migration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmigration.proto\x12\x10processmigration\" \n\x11\x43heckpointRequest\x12\x0b\n\x03pid\x18\x01 \x01(\x05\"&\n\x12\x43heckpointResponse\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\"\n\x0eRestoreRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\".\n\x0fRestoreResponse\x12\x0b\n\x03pid\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\"9\n\x0eMigrateRequest\x12\x12\n\nsource_pid\x18\x01 \x01(\x05\x12\x13\n\x0btarget_host\x18\x02 \x01(\t\"5\n\x0fMigrateResponse\x12\x12\n\ntarget_pid\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t2\x8b\x02\n\x10ProcessMigration\x12W\n\nCheckpoint\x12#.processmigration.CheckpointRequest\x1a$.processmigration.CheckpointResponse\x12N\n\x07Restore\x12 .processmigration.RestoreRequest\x1a!.processmigration.RestoreResponse\x12N\n\x07Migrate\x12 .processmigration.MigrateRequest\x1a!.processmigration.MigrateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'migration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKPOINTREQUEST']._serialized_start=37
  _globals['_CHECKPOINTREQUEST']._serialized_end=69
  _globals['_CHECKPOINTRESPONSE']._serialized_start=71
  _globals['_CHECKPOINTRESPONSE']._serialized_end=109
  _globals['_RESTOREREQUEST']._serialized_start=111
  _globals['_RESTOREREQUEST']._serialized_end=145
  _globals['_RESTORERESPONSE']._serialized_start=147
  _globals['_RESTORERESPONSE']._serialized_end=193
  _globals['_MIGRATEREQUEST']._serialized_start=195
  _globals['_MIGRATEREQUEST']._serialized_end=252
  _globals['_MIGRATERESPONSE']._serialized_start=254
  _globals['_MIGRATERESPONSE']._serialized_end=307
  _globals['_PROCESSMIGRATION']._serialized_start=310
  _globals['_PROCESSMIGRATION']._serialized_end=577
# @@protoc_insertion_point(module_scope)
