# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import migration_pb2 as migration__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in migration_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProcessMigrationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Checkpoint = channel.unary_unary(
                '/processmigration.ProcessMigration/Checkpoint',
                request_serializer=migration__pb2.CheckpointRequest.SerializeToString,
                response_deserializer=migration__pb2.CheckpointResponse.FromString,
                _registered_method=True)
        self.Restore = channel.unary_unary(
                '/processmigration.ProcessMigration/Restore',
                request_serializer=migration__pb2.RestoreRequest.SerializeToString,
                response_deserializer=migration__pb2.RestoreResponse.FromString,
                _registered_method=True)
        self.Migrate = channel.unary_unary(
                '/processmigration.ProcessMigration/Migrate',
                request_serializer=migration__pb2.MigrateRequest.SerializeToString,
                response_deserializer=migration__pb2.MigrateResponse.FromString,
                _registered_method=True)


class ProcessMigrationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Checkpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Restore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Migrate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessMigrationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Checkpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.Checkpoint,
                    request_deserializer=migration__pb2.CheckpointRequest.FromString,
                    response_serializer=migration__pb2.CheckpointResponse.SerializeToString,
            ),
            'Restore': grpc.unary_unary_rpc_method_handler(
                    servicer.Restore,
                    request_deserializer=migration__pb2.RestoreRequest.FromString,
                    response_serializer=migration__pb2.RestoreResponse.SerializeToString,
            ),
            'Migrate': grpc.unary_unary_rpc_method_handler(
                    servicer.Migrate,
                    request_deserializer=migration__pb2.MigrateRequest.FromString,
                    response_serializer=migration__pb2.MigrateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'processmigration.ProcessMigration', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('processmigration.ProcessMigration', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProcessMigration(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Checkpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/processmigration.ProcessMigration/Checkpoint',
            migration__pb2.CheckpointRequest.SerializeToString,
            migration__pb2.CheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Restore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/processmigration.ProcessMigration/Restore',
            migration__pb2.RestoreRequest.SerializeToString,
            migration__pb2.RestoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Migrate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/processmigration.ProcessMigration/Migrate',
            migration__pb2.MigrateRequest.SerializeToString,
            migration__pb2.MigrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
